### ISSUE TITLE
Can't create archive object file type: 1

### ISSUE THREAD

**Issue by devjiangzhou** [OlehKulykov/LzmaSDKObjC#9]
ERROR: code = -1, file = '/Users/xxx/Desktop/LzmaSDKObjC-0.0.8/src/LzmaSDKObjCFileDecoder.cpp', line = 185, description = Can't create archive object file type: 12016-03-28 17:53:04:357 TaeExam[3465:668038] Open error: Error Domain=LzmaSDKObjCReader Code=-1 "Can't create archive object file type: 1" UserInfo={code=-1, line=185, file=/Users/xxx/Desktop/LzmaSDKObjC-0.0.8/src/LzmaSDKObjCFileDecoder.cpp, NSLocalizedDescription=Can't create archive object file type: 1}

I‘m use static Libray，LzmaSDKObjC-0.0.8，

**Comment by OlehKulykov** [comment]
Hi,

this problem cause of using static library. Commonly say - don't use static. Why? Cause of compiller ignores code of the LZMA SDK initialization and in a result LZMA initializer can get available plugins.

Plz use latests _pod 'LzmaSDK-ObjC'_ instead of _LzmaSDKObjC-0.0.8_ , which is deprecated due to iOS 8.- dynamic fremeworks functionality.

**Comment by OlehKulykov** [comment]
If it's for you possible & not strict - you could provide some test archive with any content and mocup password to check.
